# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    recipe_service:
        class: CookWithMeBundle\Services\RecipeService
        arguments: [@recipe_manager]

    recipe_manager:
        class: CookWithMeBundle\Managers\RecipeManager
        arguments: [@doctrine.orm.default_entity_manager]

    step_service:
        class: CookWithMeBundle\Services\StepService
        arguments: [@step_manager]

    step_manager:
        class: CookWithMeBundle\Managers\StepManager
        arguments: [@doctrine.orm.default_entity_manager]